
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetUserHistory
{

    public int Id { get; set; }

    public string TaiKhoan { get; set; }

    public Nullable<System.DateTime> ThoiGianTao { get; set; }

    public string TrangThai { get; set; }

    public string IP { get; set; }

}

}
