//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_V2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_KSAT_VITRI_CONGC_SDUNG
    {
        public int ID { get; set; }
        public string ID_VITRI { get; set; }
        public string TEN_VITRI { get; set; }
        public Nullable<int> ID_BB { get; set; }
        public string TEN_CONGCU { get; set; }
        public Nullable<int> ID_CONGCU { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    }
}
