//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_V2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBAN_KSAT_HTRUONG
    {
        public int ID { get; set; }
        public string TEN { get; set; }
        public string TINH_TRANG { get; set; }
        public string NGUOI_LAP { get; set; }
        public string NGUOI_DUYET { get; set; }
        public Nullable<System.DateTime> NGAY_LAP { get; set; }
        public Nullable<System.DateTime> NGAY_DUYET { get; set; }
    }
}
