
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class BBAN_KSAT_VITRI
{

    public int ID { get; set; }

    public Nullable<int> ID_BB { get; set; }

    public string ID_VITRI_PMIS { get; set; }

    public string TEN_VITRI { get; set; }

    public string LOAI_CVIEC { get; set; }

    public string NDUNG_CVIEC { get; set; }

    public string PAN_THIEN { get; set; }

    public string BPHAP_ATOAN { get; set; }

    public string CCU_DCU { get; set; }

}

}
