
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class CAM_PHIENLV
{

    public string CAM_ID { get; set; }

    public int PHIEN_ID { get; set; }

    public Nullable<bool> IS_ACTIVE { get; set; }

    public string MA_DVIQLY { get; set; }

}

}
