
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class hlat_TaiNan
{

    public int Id { get; set; }

    public string DonViId { get; set; }

    public string DiaChi { get; set; }

    public int Quy { get; set; }

    public int Nam { get; set; }

    public int CapDienApId { get; set; }

    public Nullable<int> SoLuongVu { get; set; }

    public string HoTenNN { get; set; }

    public Nullable<int> TuoiNN { get; set; }

    public string NgheNghiepNN { get; set; }

    public Nullable<System.DateTime> NgayXayRa { get; set; }

    public Nullable<int> PhanLoai_NguyenNhan { get; set; }

    public string NguyenNhan_DienBien { get; set; }

    public Nullable<int> TinhTrang { get; set; }

    public string GhiChu { get; set; }

    public Nullable<bool> IsChuyenNPC { get; set; }

    public string NguoiChuyenNPC { get; set; }

    public Nullable<System.DateTime> NgayChuyenNPC { get; set; }

    public System.DateTime NgayTao { get; set; }

    public string NguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public string NguoiSua { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<System.DateTime> NgayXoa { get; set; }

    public string NguoiXoa { get; set; }

    public int TrangThai { get; set; }

}

}
