
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class hlat_PhaDat
{

    public int Id { get; set; }

    public string DonViId { get; set; }

    public int Thang { get; set; }

    public int Nam { get; set; }

    public int CapDienApId { get; set; }

    public Nullable<int> Tong_DauNam { get; set; }

    public Nullable<int> Tong_LuyKe { get; set; }

    public Nullable<int> TangGiam_PhatSinhMoi { get; set; }

    public Nullable<int> TangGiam_GiamDoCaiTao { get; set; }

    public Nullable<int> TangGiam_GiamDoPhoiHopDiaPhuong { get; set; }

    public string DoVong { get; set; }

    public string DanhGiaDoNguyHiem { get; set; }

    public Nullable<double> CayCoi_TrongHL { get; set; }

    public Nullable<double> CayCoi_NgoaiHL { get; set; }

    public Nullable<double> CayCoi_DiemHRN { get; set; }

    public string GhiChu { get; set; }

    public Nullable<bool> IsChuyenNPC { get; set; }

    public string NguoiChuyenNPC { get; set; }

    public Nullable<System.DateTime> NgayChuyenNPC { get; set; }

    public System.DateTime NgayTao { get; set; }

    public string NguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public string NguoiSua { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<System.DateTime> NgayXoa { get; set; }

    public string NguoiXoa { get; set; }

    public int TrangThai { get; set; }

}

}
