
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class HLENH_ATOAN_CTIET
{

    public Nullable<int> ID_HL { get; set; }

    public int ID { get; set; }

    public string BUOC { get; set; }

    public Nullable<int> STT_BUOC { get; set; }

    public string File_Amthanh { get; set; }

    public string NOI_DUNG { get; set; }

    public Nullable<bool> IsVideo { get; set; }

}

}
