
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class KTDK_NHOMKTR
{

    public string MA_LOAI_KTR { get; set; }

    public string TEN_LOAI_KTR { get; set; }

    public int STT { get; set; }

    public string MO_TA { get; set; }

}

}
