
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class KTDK_XLTT
{

    public int ID_PHIEN { get; set; }

    public string ID_TONTAI { get; set; }

    public string LOAI_XLY { get; set; }

}

}
