
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class KTDK_PHIENLV
{

    public int id_phien { get; set; }

    public string assetid { get; set; }

    public string id_loaiktr { get; set; }

    public string assetdesc { get; set; }

    public string typeid { get; set; }

    public string ghichu { get; set; }

}

}
