
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class KTDK_LOAIKTR
{

    public Nullable<int> STT { get; set; }

    public string MA_NHOM_KTR { get; set; }

    public string ID_LOAIKTR { get; set; }

    public string TEN_LOAIKTR { get; set; }

    public string TYPEID { get; set; }

    public Nullable<int> TAN_SUAT { get; set; }

    public string MA_LOAI_KTR { get; set; }

}

}
