//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_V2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTDK_TBI_LOAI
    {
        public string ASSETID { get; set; }
        public string ID_LOAIKTR { get; set; }
        public Nullable<int> TANSUAT { get; set; }
        public Nullable<System.DateTime> NGAY_TH_MAX { get; set; }
    }
}
