//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_V2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.MenuOfRoles = new HashSet<MenuOfRole>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> Level { get; set; }
        public string Code { get; set; }
        public string Text { get; set; }
        public string Order { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string Class { get; set; }
        public Nullable<bool> IsNewLetter { get; set; }
        public Nullable<bool> IsFrontPage { get; set; }
        public Nullable<bool> IsShowMenu { get; set; }
        public Nullable<int> RoleView { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public string NguoiXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuOfRole> MenuOfRoles { get; set; }
    }
}
