
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class MenuOfRole
{

    public int Id { get; set; }

    public string RoleId { get; set; }

    public int MenuId { get; set; }

    public bool Status { get; set; }



    public virtual AspNetRole AspNetRole { get; set; }

    public virtual Menu Menu { get; set; }

}

}
