//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_V2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLV_PAN_TCONG
    {
        public int ID { get; set; }
        public Nullable<int> ID_PLV { get; set; }
        public string ID_VITRI_PMIS { get; set; }
        public Nullable<int> ID_BBAN { get; set; }
    }
}
