
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class plv_PhieuCongTac_Sign
{

    public int Id { get; set; }

    public int MaPCT { get; set; }

    public int PhienLamViecID { get; set; }

    public int Step { get; set; }

    public string UserSign { get; set; }

    public Nullable<System.DateTime> DateSign { get; set; }

    public string UrlFileSign { get; set; }

    public string UserSignId { get; set; }

    public string ChucVu { get; set; }

}

}
