
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class plv_LichSuCapSoPhieu_His
{

    public int ID { get; set; }

    public string SoPhieu { get; set; }

    public string NguoiTao { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<int> MaLP { get; set; }

    public string DonViId { get; set; }

    public Nullable<bool> IsHand { get; set; }

    public Nullable<int> MaPCT { get; set; }

    public Nullable<int> Thang { get; set; }

    public Nullable<int> Nam { get; set; }

    public Nullable<int> TramId { get; set; }

}

}
