//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_V2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLY_RRO
    {
        public int ID { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<int> ID_LOAI { get; set; }
        public string TRANG_THAI { get; set; }
        public string BIEN_PHAP { get; set; }
        public string ND_KHAC_PHUC { get; set; }
        public Nullable<System.DateTime> NGAY_NHAP { get; set; }
        public string NGUOI_NHAP { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public string NGUOI_SUA { get; set; }
        public string MA_DV { get; set; }
        public string ID_VITRI_PMIS { get; set; }
        public string TEN_VITRI { get; set; }
    }
}
