//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_V2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_KHGiaoTGXLSCTHA
    {
        public int Id { get; set; }
        public int Nam { get; set; }
        public string DonViId { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NguoiNhap { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<double> TrungBinhNam { get; set; }
        public Nullable<double> Thang1 { get; set; }
        public Nullable<double> Thang2 { get; set; }
        public Nullable<double> Thang3 { get; set; }
        public Nullable<double> Thang4 { get; set; }
        public Nullable<double> Thang5 { get; set; }
        public Nullable<double> Thang6 { get; set; }
        public Nullable<double> Thang7 { get; set; }
        public Nullable<double> Thang8 { get; set; }
        public Nullable<double> Thang9 { get; set; }
        public Nullable<double> Thang10 { get; set; }
        public Nullable<double> Thang11 { get; set; }
        public Nullable<double> Thang12 { get; set; }
        public Nullable<double> TrungBinhNamDC { get; set; }
        public Nullable<bool> IsOpenNam { get; set; }
        public Nullable<double> Thang1DC { get; set; }
        public Nullable<double> Thang2DC { get; set; }
        public Nullable<double> Thang3DC { get; set; }
        public Nullable<double> Thang4DC { get; set; }
        public Nullable<double> Thang5DC { get; set; }
        public Nullable<double> Thang6DC { get; set; }
        public Nullable<double> Thang7DC { get; set; }
        public Nullable<double> Thang8DC { get; set; }
        public Nullable<double> Thang9DC { get; set; }
        public Nullable<double> Thang10DC { get; set; }
        public Nullable<double> Thang11DC { get; set; }
        public Nullable<double> Thang12DC { get; set; }
        public Nullable<bool> IsOpenT1 { get; set; }
        public Nullable<bool> IsOpenT2 { get; set; }
        public Nullable<bool> IsOpenT3 { get; set; }
        public Nullable<bool> IsOpenT4 { get; set; }
        public Nullable<bool> IsOpenT5 { get; set; }
        public Nullable<bool> IsOpenT6 { get; set; }
        public Nullable<bool> IsOpenT7 { get; set; }
        public Nullable<bool> IsOpenT8 { get; set; }
        public Nullable<bool> IsOpenT9 { get; set; }
        public Nullable<bool> IsOpenT10 { get; set; }
        public Nullable<bool> IsOpenT11 { get; set; }
        public Nullable<bool> IsOpenT12 { get; set; }
        public Nullable<System.DateTime> NPCNgayMo { get; set; }
        public string NPCNguoiMo { get; set; }
    }
}
