
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class sc_ThietBiSuCo
{

    public int Id { get; set; }

    public int SuCoId { get; set; }

    public Nullable<int> MaHieuId { get; set; }

    public Nullable<int> NhaSanXuatId { get; set; }

    public Nullable<int> DonViTinhId { get; set; }

    public string SoHD { get; set; }

    public string BienBanNT { get; set; }

    public string TenDonViThiCong { get; set; }

    public Nullable<System.DateTime> NgaySanXuat { get; set; }

    public string LichSuVanHanh { get; set; }

    public Nullable<System.DateTime> NgayDongDien { get; set; }

    public string MoiTruongVH { get; set; }

    public Nullable<int> SoLuong { get; set; }

    public string GhiChu { get; set; }

    public System.DateTime NgayTao { get; set; }

    public string NguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public string NguoiSua { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<System.DateTime> NgayXoa { get; set; }

    public string NguoiXoa { get; set; }

    public int TrangThai { get; set; }

}

}
