
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_NhanVien_PhienLamViec_His
{

    public int PhienLamViecId { get; set; }

    public int VaiTroPhienLamViecId { get; set; }

    public string NhanVienId { get; set; }

    public string DonViId { get; set; }

    public Nullable<int> PhongBanId { get; set; }

}

}
