//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_V2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDevice
    {
        public string ID { get; set; }
        public string TOKENKEY { get; set; }
        public string MACHINE_TYPE { get; set; }
        public string userid { get; set; }
        public string username { get; set; }
    }
}
