//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_V2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKTG
    {
        public string ID { get; set; }
        public Nullable<int> MA_PCT { get; set; }
        public string DonViId { get; set; }
        public Nullable<int> ID_PLV { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string DonViCoSo { get; set; }
        public string NoiDungCongViec { get; set; }
        public string DanhGiaY1 { get; set; }
        public string DanhGiaY2 { get; set; }
        public string DanhGiaY3 { get; set; }
        public string DanhGiaY4 { get; set; }
        public string DanhGiaY5 { get; set; }
        public string DanhGiaY6 { get; set; }
        public string DanhGiaY7 { get; set; }
        public string DanhGiaY8 { get; set; }
        public string DanhGiaY9 { get; set; }
        public string Nguoi_CHTT { get; set; }
        public string DaiDienDVCS { get; set; }
        public string DaiDienDoan { get; set; }
        public string TP_KT1 { get; set; }
        public string TP_KT2 { get; set; }
        public string TP_KT_CS1 { get; set; }
        public string TP_KT_CS2 { get; set; }
        public string NguoiChiHuyTT { get; set; }
        public string NguoiGSAT { get; set; }
        public Nullable<System.DateTime> ThoiGianKT { get; set; }
        public string NguoiKT { get; set; }
        public Nullable<bool> KetThuc { get; set; }
        public Nullable<bool> CoTonTai { get; set; }
        public string Nguoi_Tao { get; set; }
        public string Loai_KTGS { get; set; }
    }
}
