//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECP_V2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTagImageUser
    {
        public long Id { get; set; }
        public Nullable<long> TagId { get; set; }
        public Nullable<long> ImageId { get; set; }
        public string UserId { get; set; }
    }
}
