
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class vs_Comment
{

    public int Id { get; set; }

    public int BaoCaoId { get; set; }

    public string NoiDung { get; set; }

    public int Type { get; set; }

    public System.DateTime NgayTao { get; set; }

    public string NguoiTao { get; set; }

}

}
