
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECP_V2.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class vs_HinhAnh
{

    public int Id { get; set; }

    public int NoiDungId { get; set; }

    public int Type { get; set; }

    public string Url { get; set; }

    public string Name { get; set; }

    public string FileType { get; set; }

    public Nullable<long> FileSize { get; set; }

    public Nullable<decimal> Longtitude { get; set; }

    public Nullable<decimal> Latitude { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime DateCreated { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }

    public int Status { get; set; }

}

}
